apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
  namespace: default
spec:
  rules:
  - host: ppd.mysql.com
    http:
      paths: 
      - backend:
          serviceName: mysql
          servicePort: 3306
