apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  namespace: mysql
  labels:
    app: mysql
    version: "8.0.22"
data:
 host: mysql
 name: rdsapp
 my.cnf: |
    [mysqld]
    max_connections = 600
    read_buffer_size = 1048576
    net_read_timeout = 360
    net_write_timeout = 360
