apiVersion: v1
kind: Service
metadata:
  name: rdsapp1-service
  namespace: default
spec:
  selector:           
    app: rdsapp1
  ports:
  - name: http
    nodePort: 30001
    port: 8880
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30002
    port: 8880
    protocol: TCP
    targetPort: 8080
  type: NodePort
