apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rdsapp-depl
  name: rdsapp-depl
  namespace: default
  resourceVersion: "2974"
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rdsapp-depl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rdsapp-depl
    spec:
      containers:
      - image: akumar6030/rdsapp1:4
        imagePullPolicy: IfNotPresent
        name: rdsapp1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
