apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2021-07-17T06:09:47Z"
  generation: 5
  labels:
    app: rdsapp-depl
  name: rdsapp-depl
  namespace: default
  resourceVersion: "2974"
  uid: 65f65098-129c-431c-a223-2b1815b0c98f
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rdsapp-depl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rdsapp-depl
    spec:
      containers:
      - image: akumar6030/rdsapp1:4
        imagePullPolicy: IfNotPresent
        name: rdsapp1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-07-17T06:15:23Z"
    lastUpdateTime: "2021-07-17T06:15:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable