apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rdsapp
  name: rdsapp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rdsapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rdsapp
    spec:
      containers:
      - image: akumar6030/rdsapp1:5
        imagePullPolicy: IfNotPresent
        name: rdsapp1
        ports: 
          containerPort: 8088
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env: 
        - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
